### ISSUE TITLE
Precompile binaries

### ISSUE THREAD

**Issue by nebrius** [nebrius/raspi#1]
We should ship precompiled binaries of raspi-core, and all other raspi modules with C++. Only one architecture is being targeted, obviously, so it doesn't make sense to recompile at install time.

**Comment by bestander** [comment]
:+1:

**Comment by bestander** [comment]
I am a complete noob here.
Isn't Raspberry Pi 1 an ARMV6 while Raspberry Pi 2 an ARMV7?
Are they binary compatible?

**Comment by nebrius** [comment]
Yeah that changed since I crea this task, and we now also have to support more than one version of node, which also requires different binaries. Fortunately there's a module called node-pre-gyp to make this easier.

**Comment by nebrius** [comment]
I switched to using pigpio, so there is no longer native code in this module.
