### ISSUE TITLE
Jessie and node 4.2.1 ?

### ISSUE THREAD

**Issue by teuteuguy** [nebrius/raspi#3]
Hi,
I've just tried installing raspi, however it failed on npm install.

Could there be an incompatibility with Jessie and node 4.2.1 ?

Cheers

**Comment by nebrius** [comment]
Unfortunately node 4 is not supported yet. You can track the upgrade progress at https://github.com/nebrius/raspi-io/issues/35.

In the meantime, I recommend using node 0.12
